2024-06-22 00:06:01 | ERROR | (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'TRANSACTION' at line 1")
2024-06-22 00:06:01 | ERROR | Traceback (most recent call last):
  File "A:\flask_ai_app\src\services\AdminService.py", line 28, in index
    cursor.execute("BEGIN TRANSACTION")
  File "A:\flask_ai_app\.venv\Lib\site-packages\pymysql\cursors.py", line 153, in execute
    result = self._query(query)
             ^^^^^^^^^^^^^^^^^^
  File "A:\flask_ai_app\.venv\Lib\site-packages\pymysql\cursors.py", line 322, in _query
    conn.query(q)
  File "A:\flask_ai_app\.venv\Lib\site-packages\pymysql\connections.py", line 563, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "A:\flask_ai_app\.venv\Lib\site-packages\pymysql\connections.py", line 825, in _read_query_result
    result.read()
  File "A:\flask_ai_app\.venv\Lib\site-packages\pymysql\connections.py", line 1199, in read
    first_packet = self.connection._read_packet()
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "A:\flask_ai_app\.venv\Lib\site-packages\pymysql\connections.py", line 775, in _read_packet
    packet.raise_for_error()
  File "A:\flask_ai_app\.venv\Lib\site-packages\pymysql\protocol.py", line 219, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "A:\flask_ai_app\.venv\Lib\site-packages\pymysql\err.py", line 150, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.ProgrammingError: (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'TRANSACTION' at line 1")

2024-06-22 00:07:39 | ERROR | (1054, "Unknown column 'last_activity' in 'field list'")
2024-06-22 00:07:39 | ERROR | Traceback (most recent call last):
  File "A:\flask_ai_app\src\services\AdminService.py", line 33, in index
    cursor.execute("INSERT INTO tester (`id`, `type`, `name`, `number_phone`, `created_at`, `ban`, `last_activity`) VALUES (NULL, 'tester', %(name)s, %(number_phone)s, NOW(), FALSE, NULL)", {'name': user.name, 'number_phone': user.number})
  File "A:\flask_ai_app\.venv\Lib\site-packages\pymysql\cursors.py", line 153, in execute
    result = self._query(query)
             ^^^^^^^^^^^^^^^^^^
  File "A:\flask_ai_app\.venv\Lib\site-packages\pymysql\cursors.py", line 322, in _query
    conn.query(q)
  File "A:\flask_ai_app\.venv\Lib\site-packages\pymysql\connections.py", line 563, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "A:\flask_ai_app\.venv\Lib\site-packages\pymysql\connections.py", line 825, in _read_query_result
    result.read()
  File "A:\flask_ai_app\.venv\Lib\site-packages\pymysql\connections.py", line 1199, in read
    first_packet = self.connection._read_packet()
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "A:\flask_ai_app\.venv\Lib\site-packages\pymysql\connections.py", line 775, in _read_packet
    packet.raise_for_error()
  File "A:\flask_ai_app\.venv\Lib\site-packages\pymysql\protocol.py", line 219, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "A:\flask_ai_app\.venv\Lib\site-packages\pymysql\err.py", line 150, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1054, "Unknown column 'last_activity' in 'field list'")

2024-06-22 00:32:29 | ERROR | Error code: 403 - {'error': {'type': 'forbidden', 'message': 'Request not allowed'}}
2024-06-22 00:32:29 | ERROR | Traceback (most recent call last):
  File "A:\flask_ai_app\src\services\ChatService.py", line 90, in choose_model_precdition
    return ClaudeCore(self.client, mx_tk=self.mx_tokens).precdition(prompt)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "A:\flask_ai_app\src\ai_llms\ClaudeAI.py", line 42, in precdition
    message = self.client.messages.create(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "A:\flask_ai_app\.venv\Lib\site-packages\anthropic\_utils\_utils.py", line 277, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "A:\flask_ai_app\.venv\Lib\site-packages\anthropic\resources\messages.py", line 904, in create
    return self._post(
           ^^^^^^^^^^^
  File "A:\flask_ai_app\.venv\Lib\site-packages\anthropic\_base_client.py", line 1249, in post
    return cast(ResponseT, self.request(cast_to, opts, stream=stream, stream_cls=stream_cls))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "A:\flask_ai_app\.venv\Lib\site-packages\anthropic\_base_client.py", line 931, in request
    return self._request(
           ^^^^^^^^^^^^^^
  File "A:\flask_ai_app\.venv\Lib\site-packages\anthropic\_base_client.py", line 1029, in _request
    raise self._make_status_error_from_response(err.response) from None
anthropic.PermissionDeniedError: Error code: 403 - {'error': {'type': 'forbidden', 'message': 'Request not allowed'}}

2024-06-22 00:33:29 | ERROR | Error code: 403 - {'error': {'type': 'forbidden', 'message': 'Request not allowed'}}
2024-06-22 00:33:29 | ERROR | Traceback (most recent call last):
  File "A:\flask_ai_app\src\services\ChatService.py", line 90, in choose_model_precdition
    return ClaudeCore(self.client, mx_tk=self.mx_tokens).precdition(prompt)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "A:\flask_ai_app\src\ai_llms\ClaudeAI.py", line 42, in precdition
    message = self.client.messages.create(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "A:\flask_ai_app\.venv\Lib\site-packages\anthropic\_utils\_utils.py", line 277, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "A:\flask_ai_app\.venv\Lib\site-packages\anthropic\resources\messages.py", line 904, in create
    return self._post(
           ^^^^^^^^^^^
  File "A:\flask_ai_app\.venv\Lib\site-packages\anthropic\_base_client.py", line 1249, in post
    return cast(ResponseT, self.request(cast_to, opts, stream=stream, stream_cls=stream_cls))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "A:\flask_ai_app\.venv\Lib\site-packages\anthropic\_base_client.py", line 931, in request
    return self._request(
           ^^^^^^^^^^^^^^
  File "A:\flask_ai_app\.venv\Lib\site-packages\anthropic\_base_client.py", line 1029, in _request
    raise self._make_status_error_from_response(err.response) from None
anthropic.PermissionDeniedError: Error code: 403 - {'error': {'type': 'forbidden', 'message': 'Request not allowed'}}

2024-06-22 00:33:33 | ERROR | Error code: 400 - {'type': 'error', 'error': {'type': 'invalid_request_error', 'message': 'messages: roles must alternate between "user" and "assistant", but found multiple "user" roles in a row'}}
2024-06-22 00:33:33 | ERROR | Traceback (most recent call last):
  File "A:\flask_ai_app\src\services\ChatService.py", line 90, in choose_model_precdition
    return ClaudeCore(self.client, mx_tk=self.mx_tokens).precdition(prompt)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "A:\flask_ai_app\src\ai_llms\ClaudeAI.py", line 42, in precdition
    message = self.client.messages.create(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "A:\flask_ai_app\.venv\Lib\site-packages\anthropic\_utils\_utils.py", line 277, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "A:\flask_ai_app\.venv\Lib\site-packages\anthropic\resources\messages.py", line 904, in create
    return self._post(
           ^^^^^^^^^^^
  File "A:\flask_ai_app\.venv\Lib\site-packages\anthropic\_base_client.py", line 1249, in post
    return cast(ResponseT, self.request(cast_to, opts, stream=stream, stream_cls=stream_cls))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "A:\flask_ai_app\.venv\Lib\site-packages\anthropic\_base_client.py", line 931, in request
    return self._request(
           ^^^^^^^^^^^^^^
  File "A:\flask_ai_app\.venv\Lib\site-packages\anthropic\_base_client.py", line 1029, in _request
    raise self._make_status_error_from_response(err.response) from None
anthropic.BadRequestError: Error code: 400 - {'type': 'error', 'error': {'type': 'invalid_request_error', 'message': 'messages: roles must alternate between "user" and "assistant", but found multiple "user" roles in a row'}}

2024-06-22 00:34:11 | ERROR | Error code: 400 - {'type': 'error', 'error': {'type': 'invalid_request_error', 'message': 'messages: roles must alternate between "user" and "assistant", but found multiple "user" roles in a row'}}
2024-06-22 00:34:11 | ERROR | Traceback (most recent call last):
  File "A:\flask_ai_app\src\services\ChatService.py", line 90, in choose_model_precdition
    return ClaudeCore(self.client, mx_tk=self.mx_tokens).precdition(prompt)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "A:\flask_ai_app\src\ai_llms\ClaudeAI.py", line 42, in precdition
    message = self.client.messages.create(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "A:\flask_ai_app\.venv\Lib\site-packages\anthropic\_utils\_utils.py", line 277, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "A:\flask_ai_app\.venv\Lib\site-packages\anthropic\resources\messages.py", line 904, in create
    return self._post(
           ^^^^^^^^^^^
  File "A:\flask_ai_app\.venv\Lib\site-packages\anthropic\_base_client.py", line 1249, in post
    return cast(ResponseT, self.request(cast_to, opts, stream=stream, stream_cls=stream_cls))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "A:\flask_ai_app\.venv\Lib\site-packages\anthropic\_base_client.py", line 931, in request
    return self._request(
           ^^^^^^^^^^^^^^
  File "A:\flask_ai_app\.venv\Lib\site-packages\anthropic\_base_client.py", line 1029, in _request
    raise self._make_status_error_from_response(err.response) from None
anthropic.BadRequestError: Error code: 400 - {'type': 'error', 'error': {'type': 'invalid_request_error', 'message': 'messages: roles must alternate between "user" and "assistant", but found multiple "user" roles in a row'}}

2024-06-22 00:34:58 | ERROR | Error code: 400 - {'type': 'error', 'error': {'type': 'invalid_request_error', 'message': 'messages: roles must alternate between "user" and "assistant", but found multiple "user" roles in a row'}}
2024-06-22 00:34:58 | ERROR | Traceback (most recent call last):
  File "A:\flask_ai_app\src\services\ChatService.py", line 90, in choose_model_precdition
    return ClaudeCore(self.client, mx_tk=self.mx_tokens).precdition(prompt)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "A:\flask_ai_app\src\ai_llms\ClaudeAI.py", line 42, in precdition
    message = self.client.messages.create(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "A:\flask_ai_app\.venv\Lib\site-packages\anthropic\_utils\_utils.py", line 277, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "A:\flask_ai_app\.venv\Lib\site-packages\anthropic\resources\messages.py", line 904, in create
    return self._post(
           ^^^^^^^^^^^
  File "A:\flask_ai_app\.venv\Lib\site-packages\anthropic\_base_client.py", line 1249, in post
    return cast(ResponseT, self.request(cast_to, opts, stream=stream, stream_cls=stream_cls))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "A:\flask_ai_app\.venv\Lib\site-packages\anthropic\_base_client.py", line 931, in request
    return self._request(
           ^^^^^^^^^^^^^^
  File "A:\flask_ai_app\.venv\Lib\site-packages\anthropic\_base_client.py", line 1029, in _request
    raise self._make_status_error_from_response(err.response) from None
anthropic.BadRequestError: Error code: 400 - {'type': 'error', 'error': {'type': 'invalid_request_error', 'message': 'messages: roles must alternate between "user" and "assistant", but found multiple "user" roles in a row'}}

